### ISSUE TITLE
Problem with building Caribou 

### ISSUE THREAD

**Issue by dabou2010** [mimesis-inria/DeepPhysX#11]
Hello

I have been trying to build Caribou so I can use DeepPysX.Sofa examples but I have been facing this problem both on windows 10 and similar on ubuntu 22.04

```
CMake Error at C:/Program Files/CMake/share/cmake-3.25/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Boost (missing: Boost_INCLUDE_DIR)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.25/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files/CMake/share/cmake-3.25/Modules/FindBoost.cmake:2377 (find_package_handle_standard_args)
  E:/SOFA/SOFA_v22.12.00_Win64/lib/cmake/Sofa.Type/Sofa.TypeConfig.cmake:34 (find_package)
  E:/SOFA/SOFA_v22.12.00_Win64/lib/cmake/SofaFramework/SofaFrameworkConfig.cmake:37 (find_package)
  cmake/FindSOFA.cmake:19 (find_package)
  CMakeLists.txt:57 (find_package)
```

Is there a way to solve this problem,

**Comment by dabou2010** [comment]
For anyone facing this problem, apparently I'm facing this problem because I'm using a ready binary version of Sofa without building it from scratch. So I followed the steps as if I'm building Sofa by installing boost and Qt5.

But now I'm facing this problem

```
CMake Error at build/cmake/Caribou/TopologyConfig.cmake:30 (find_package):
  Could not find a package configuration file provided by "Eigen3" with any
  of the following names:

    Eigen3Config.cmake
    eigen3-config.cmake
```
I downloaded eigen and add it to the PATH env variable but still exist.

**Comment by RobinEnjalbert** [comment]
I @dabou2010 ,

Did you tried to install the binary version of Caribou( [these instructions](https://github.com/mimesis-inria/caribou#quick-installation)) or to build from sources ([these instructions](https://caribou.readthedocs.io/en/latest/Building.html#prerequisites-sofacaribou-optional)) ?

**Comment by dabou2010** [comment]
hello @RobinEnjalbert 

I abandonded the installation on windows and installed it on ubuntu 20.04, I followed the instructions of building from source and I just got it to work.

I want to mention there's a bug in the demos, in the instruction of building from source you refer to the build of Caribou as CARIBOU_ROOT, but in the demos it looks for CARINOU_INSTALL, like in
`SofaRuntime.PluginRepository.addFirstPath(os.environ['CARIBOU_INSTALL'])
`

**Comment by RobinEnjalbert** [comment]
Hi @dabou2010 ,

Glad to see your installation is working now ! 
About the `CARIBOU_INSTALL` environment variable, it seems that the doc of Caribou changed since when I implemented the demos, so I will update it. Thanks for reporting this.
